name: Unit Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '3.2'
        - '3.1'
        - '3.0'
        - '2.7'
        - jruby
    env:
      RAILS_ENV: test
      GH_ACTIONS_UNIT_TESTS: 1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Run RSpec tests
        run: |
          bundle exec rspec
